### ISSUE TITLE
Question: DefaultSettings Re-encode

### ISSUE THREAD

**Issue by allogator** [ptr727/PlexCleaner#101]
Apologies, I couldn't find a way to just ask you a question.

I primarily use a Roku and saw your note "Some H.264 video profiles like "Constrained Baseline@30" cause hangs on Roku, re-encode to H.264 "High@40"."

The default settings show:
"Format": "h264",
        "Profile": "Constrained Baseline@30"

So does that mean it is encoding FROM Constrained Baseline@30 or should I change that in the file to High@40 since I'm 99% Roku based?

**Comment by ptr727** [comment]
The config is for matching of existing content, not desired output, so any content that matches from the list will be re-encoded.
With the default options if any of your media is Constrained Baseline@30 it will be re-encoded.

**Comment by allogator** [comment]
Thanks!
