### ISSUE TITLE
HanbrakeCLI PPA provided by stebbins is no longer maintained

### ISSUE THREAD

**Issue by ptr727** [ptr727/PlexCleaner#119]
GitHub action builds started failing around 19 June 2022.
Issues is that the John Stebbins PPA for Handbrake is no longer being maintained, no longer available.

Old way of installing by PPA:
https://handbrake.fr/docs/en/1.0.0/get-handbrake/where-to-get-handbrake.html
https://launchpad.net/~stebbins
https://launchpad.net/~stebbins/+archive/ubuntu/handbrake-snapshots

New way of installing by flatpak:
https://handbrake.fr/docs/en/1.5.0/get-handbrake/download-and-install.html

But flatpak install requires different CLI command: `flatpak run fr.handbrake.HandBrakeCLI` vs. `HandBrakeCLI`

Figure out how to install from alternate PPA, or how to install from flatpak and launch using flatpak, or maybe compile from code.

**Comment by Traace** [comment]
The new reposity by Rob Savoury is not working because it does not contain handbrakecli thus PlexCleaner fails to process with error unable to find handbreakcli
