### ISSUE TITLE
Add support for hardware accelerated GPU encoding

### ISSUE THREAD

**Issue by ptr727** [ptr727/PlexCleaner#139]
Add support for hardware accelerated GPU encoding, e.g. NVidia Cuda, Intel QuickSync, etc.

See:
https://trac.ffmpeg.org/wiki/HWAccelIntro
https://handbrake.fr/docs/en/latest/technical/video-nvenc.html
https://handbrake.fr/docs/en/latest/technical/video-qsv.html
https://developer.nvidia.com/blog/nvidia-ffmpeg-transcoding-guide/
https://arstech.net/ffmpeg-gpu-transcoding-examples/
https://superuser.com/questions/1296374/best-settings-for-ffmpeg-with-nvenc

The code will need refactoring as the FFmpeg and Handbrake commandline options are dynamically generated, and for e.g. ffmpeg both the global and encoder options need to be set.

An option is to remove the discrete options for H264/265, quality, and audio codec should be removed and the user allowed to construct their own commandline in the JSON configuration, thus allowing for custom configurations.

**Comment by C0nw0nk** [comment]
I swear handbrake has h264/h265nvec for gpu encoding.

**Comment by ptr727** [comment]
Did you try Beta 3 that adds support?

**Comment by C0nw0nk** [comment]
> Did you try Beta 3 that adds support?

I will have a look :) Thanks prt727

**Comment by C0nw0nk** [comment]
Windows 11 64bit system

https://api.github.com/repos/ptr727/PlexCleaner/releases

https://github.com/ptr727/PlexCleaner/releases/download/3.0.35-gcfbd0d5385/PlexCleaner.7z

My Code to attempt execution stable release works fine beta throws error.
# PlexCleaner.cmd
```
@echo off & setLocal EnableDelayedExpansion

set media_path_TV="\\Con-NAS\MEDIA-SERVER\TV Shows"

set root_path="%~dp0"

"%root_path:"=%win-x64\PlexCleaner" --settingsfile "%root_path:"=%win-x64\PlexCleaner.json" defaultsettings
"%root_path:"=%win-x64\PlexCleaner" --settingsfile "%root_path:"=%win-x64\PlexCleaner.json" --logfile "%root_path:"=%win-x64\PlexCleaner.log" process --mediafiles %media_path_TV%

pause

exit
```

ERROR
```
'--settingsfile' was not matched. Did you mean one of the following?
--settingsfile
Option '--settingsfile' is required.
Unrecognized command or argument '--settingsfile'.
Unrecognized command or argument 'C:\Users\Conor\Desktop\win-x64\PlexCleaner.json'.
```


Stable release works fine but obviously no GPU encoding support :(
https://github.com/ptr727/PlexCleaner/releases/latest/download/PlexCleaner.7z

**Comment by C0nw0nk** [comment]
Ok i got it working no idea why this matters i am sure you will know @ptr727 

But this is the soloution.


```
@echo off & setLocal EnableDelayedExpansion

set media_path_TV="\\Con-NAS\MEDIA-SERVER\TV Shows"

set root_path="%~dp0"

"%root_path:"=%win-x64\PlexCleaner" defaultsettings --settingsfile "%root_path:"=%win-x64\PlexCleaner.json"
"%root_path:"=%win-x64\PlexCleaner" process --settingsfile "%root_path:"=%win-x64\PlexCleaner.json" --logfile "%root_path:"=%win-x64\PlexCleaner.log" --mediafiles %media_path_TV%

pause

exit
```

```
defaultsettings
process
```
After plexcleaner.exe in command line for some reason stable release does not care on the order of these variables.

**Comment by ptr727** [comment]
See the breaking changes section from the develop branch readme.  
https://github.com/ptr727/PlexCleaner/tree/develop

**Comment by C0nw0nk** [comment]
@ptr727 

This was my changes to your defaultsettings in beta to get GPU encoding to work on a NVIDIA GPU.

```
  "ConvertOptions": {
    "FfMpegOptions": {
      "Video": "h264_nvenc -crf 20 -preset medium",
      "Audio": "ac3",
      "Global": "-analyzeduration 2147483647 -probesize 2147483647 -hwaccel cuda -hwaccel_output_format cuda",
      "Output": "-max_muxing_queue_size 1024 -abort_on empty_output"
    },
    "HandBrakeOptions": {
      "Video": "-e nvenc_h264 --quality 20 --encoder-preset medium",
      "Audio": "copy --audio-fallback ac3"
    }
  },
```

So far works flawlessly for me :) I will leave it in this post for anyone who wants to use it.

**Comment by ptr727** [comment]
Glad to hear!

Looks pretty close to the [readme](https://github.com/ptr727/PlexCleaner/tree/develop#custom-ffmpeg-and-handbrake-cli-parameters) (I only tested QSV, don't have nvidia or amd hardware to test with). Can you please verify, and advise on changes I should make to the readme if incorrect?

**Comment by C0nw0nk** [comment]
@ptr727 Ofcourse, Thanks for a fantastic tool!

https://github.com/ptr727/PlexCleaner/issues/139#issuecomment-1501123319

So in my comment above i put h264 and h265 for Windows NVIDIA GPU's

Now with NVIDIA be it linux mac windows not any issues i have found.

I have put VAAPI for linux above to specific for AMD on Linux.

I will do a AMD WINDOWS GPU config shortly the only issue i have found so far in relation to AMD GPU's is that on ffmpeg and the gpu side it will be fine. But HandBrake does not seem to supply documentation about AMD GPU's this could be the bottleneck that still consumes CPU.


I will give AMD more looking into and provide a config for Windows users.

# AMD ENCODER WINDOWS :
### Windows:
```
h264_amf
hevc_amf
```
### Linux:
```
h264_vaapi
hevc_vaapi
```

# AMD GPU HANDBRAKE CLI encoder settings for Windows ?
```
Need to find some documentation on this.
```

### MKVTool

### MkvMerge
```
--disable-track-statistics-tags --no-global-tags --no-track-tags --no-attachments --no-buttons --normalize-language-ietf extlang --output
```

Theres a few i am looking at if they have any GPU documentation still.


### Conclusion

NVIDIA no problems at all h264 and h265 is perfect even for handbrake.

AMD is part way there just lacking in the handbrake config.

**Comment by ptr727** [comment]
Implemented in v3.
