### ISSUE TITLE
Docker logs grow "out of control"

### ISSUE THREAD

**Issue by tordenflesk** [ptr727/PlexCleaner#144]
Logs are simply growing out of control, eventually filling the filesystem.

https://i.imgur.com/OhqFzMv.png

restarting the containers doesn't clear the logs.

**Comment by ptr727** [comment]
Size of docker logs depends on your docker config, and the amount of logging done in the container, and that depends on the number of files you process.

Per google, you can control docker logging parameters:
- https://docs.docker.com/config/containers/logging/configure/
- https://docs.docker.com/compose/compose-file/#logging

E.g. compose
```
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```

E.g. run
```
docker run ... --log-opt max-size=10m --log-opt max-file=3
```

On my debian based system using `docker run -it --rm ...` to remove the container after processing exists does delete the container directory and log file in the directory.

See all logs:
- `sudo du -h $(docker inspect --format='{{.LogPath}}' $(docker ps -qa))`
- `sudo sh -c "du -ch /var/lib/docker/containers/*/*-json.log"`
