### ISSUE TITLE
MediaInfo segmentation fault on Alpine

### ISSUE THREAD

**Issue by ptr727** [ptr727/PlexCleaner#153]
```
$ mediainfo --version
MediaInfo Command line,
MediaInfoLib - v23.03
~ $ mediainfo --Output=XML "/media/VC1 - foo.mkv"
Segmentation fault
```

[Waiting](https://github.com/MediaArea/MediaInfo/issues/707) for next MediaInfo version to address the issue.

**Comment by JeromeMartinez** [comment]
Workaround (if it is what we think the source of the issue): update libzen to 0.4.41 first, then rebuild libmediainfo 23.03 (the issue is in libzen-dev).

**Comment by ptr727** [comment]
> Workaround (if it is what we think the source of the issue): update libzen to 0.4.41 first, then rebuild libmediainfo 23.03 (the issue is in libzen-dev).

Ok thx, I'll do that as I try to automate building from source.

**Comment by ptr727** [comment]
Confirmed build ling you shared works.

**Comment by ptr727** [comment]
Fixed in `MediaInfoLib - v23.04`

**Comment by ptr727** [comment]
Segfault is back in 23.07 :(

**Comment by ptr727** [comment]
Pin versions fixes the issue

**Comment by JeromeMartinez** [comment]
the issue was in old libzen, aren't new builds with newest libzen?
