### ISSUE TITLE
Tools folder or 7-Zip does not exist

### ISSUE THREAD

**Issue by Septan** [ptr727/PlexCleaner#22]
> C:\PlexCleaner>PlexCleaner.exe --settings PlexCleaner.json checkfornewtools
> 4/2/2020 10:42:26 PM : Loading settings from : "PlexCleaner.json"
> 4/2/2020 10:42:26 PM : Tools folder or 7-Zip does not exist : "C:\PlexCleaner\Tools\"

I have the folder Tools created there and have a 7Zip folder in their as well.

**Comment by ptr727** [comment]
Make sure the tools folder is correctly specified in the json config file. The default location of tools is in the same directory as the binary. Follow the readme instructions to download and copy the 7zip tools to the right location, `Tools\7Zip\x64\7za.exe`

**Comment by ptr727** [comment]
I changed the code to provide some more granular error output on the location of the tools folder and 7zip binary.
