### ISSUE TITLE
7zip download - incorrect url

### ISSUE THREAD

**Issue by xstefen** [ptr727/PlexCleaner#324]
I believe the correct URL should be `https://www.7-zip.org/a/7z2401-extra.7z` whereas currently it attempts `https://www.7-zip.org/a/7z2401 beta-extra.7z`
***
### Is this a new issue that can be reproduced using the latest version?

- [X] This is a new issue that can be reproduced.

### Which operating systems reproduce the issue?

- [X] Windows
- [ ] Docker
- [ ] Other

### Version information.

Win 11, latest
PlexCleaner, latest
Latest everything

### Steps to reproduce?

PlexCleaner checkfornewtools --settingsfile PlexCleaner.json
fails with same
manually download 7z beta extract to Tools/SevenZip
progresses further before failing with same

### Commandline.

```Text
PlexCleaner checkfornewtools --settingsfile PlexCleaner.json
```

### Relevant log output.

```Text
02:34:26 [INF] <1> SevenZip : Getting latest version ...
02:34:26 [INF] <1> SevenZip : Reading latest version from : "https://www.7-zip.org/download.html"
02:34:27 [INF] <1> SevenZip : Getting download URI details : "https://www.7-zip.org/a/7z2401 beta-extra.7z"
02:34:27 [ERR] <1> "GetContentInfo"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at InsaneGenius.Utilities.Download.GetContentInfo(Uri uri, Int64& size, DateTime& modifiedTime)
02:34:27 [ERR] <1> SevenZip : Failed to get download URI details : "https://www.7-zip.org/a/7z2401 beta-extra.7z"
02:34:27 [INF] <1> Exit Code : 1
```

### Settings file.

[PlexCleaner.json](https://github.com/ptr727/PlexCleaner/files/14191034/PlexCleaner.json)

### Log file.

https://bin.xstefen.dev/p/MiozYN.log

**Comment by ptr727** [comment]
My version regex failed for the beta text.  
I changed to getting the latest version number and downloading from GitHub instead, more deterministic.  
Can you try 3.5 pre-release and report if it works for you?

**Comment by xstefen** [comment]
Using `3.5.1-g817ea88ce9`, `05:01:39 [INF] <1> Exit Code : 0`. Well done. This docker process has been heating my room all day I'm excited to try nvenc w/o containers :)

Thx m8
