### ISSUE TITLE
Retain original creation date

### ISSUE THREAD

**Issue by Migushthe2nd** [ptr727/PlexCleaner#82]
The newly created video files all have the creation and modification timestamp of today. This messes up my photo's collection. Would it be possible to add a flag that causes PlexCleaner to copy the original dates?

**Comment by ptr727** [comment]
I could make an attempt at restoring the original timestamp if the file gets modified.
But can you elaborate on "messes up my photo's collection", what photos, why does the file timestamp matter?

**Comment by Migushthe2nd** [comment]
If I view these videos on the plex timeline they are listed at the conversion date, not the original 2007.

**Comment by ptr727** [comment]
Timeline view in plex is used for photos, and timestamps are read from exif data not from file timestamps.
I still don't understand how that is related to media files, this tool does not process photos, and it does not seem to be a use case that needs to be suported?

**Comment by Migushthe2nd** [comment]
I store family photos and videos in the same directories, sorted by year. I've created a plex library for photos that reads the main directory. Plex analyzes both photos and videos in those folders. 
This is after converting one file using PlexCleaner:
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/22274715/148655181-03e0aac5-421a-4488-b6cd-f6da43b82e05.png">

**Comment by ptr727** [comment]
I see, ok, I'll add it to the todo list.

**Comment by ptr727** [comment]
Try it out, if you add the new JSON option it will restore the last modified timestamp.

**Comment by Migushthe2nd** [comment]
Unfortunately it's not working. I was sure plex used the modification timestamp, but it must be using another header after all.
