### ISSUE TITLE
Add Shields.io badge for GHCR when available

### ISSUE THREAD

**Issue by ptr727** [ptr727/PlexCleaner#89]
See: https://github.com/badges/shields/issues/5594

**Comment by eggplants** [comment]
I have implemented [eggplants/ghcr-badge](https://github.com/eggplants/ghcr-badge) on a trial basis:

https://ghcr-badge.herokuapp.com/ptr727/plexcleaner/tags
![](https://ghcr-badge.herokuapp.com/ptr727/plexcleaner/tags)

https://ghcr-badge.herokuapp.com/ptr727/plexcleaner/latest_tag
![](https://ghcr-badge.herokuapp.com/ptr727/plexcleaner/latest_tag)

https://ghcr-badge.herokuapp.com/ptr727/plexcleaner/size
![](https://ghcr-badge.herokuapp.com/ptr727/plexcleaner/size)

Please try!

**Comment by ptr727** [comment]
How would I do something as follows, or so I need to wait for the shields.io implementation:

```
![GHCR Latest Pre-Release](https://ghcr-badge.herokuapp.com/ptr727/plexcleaner/develop_tag?logo=ghcr&color=orange)
```

**Comment by eggplants** [comment]
`label` parameter has been added. `logo` parameter is now implementing...

**Comment by ptr727** [comment]
Abandoning GHCR posting, too unreliable due to closed pipe errors that break the builds.
